### ISSUE TITLE
Should I remove semester-wise & put all the subjects all together in the navbar?

### ISSUE THREAD

**Issue by AhmedThahir** [AhmedThahir/Notes_Shared#9]

**Comment by ysh1th** [comment]
the semester-wise grouping of subjects was easier to navigate and was functional

**Comment by ysh1th** [comment]
- Current arrangement is a good one
- I agree with thermo/bio sem toggles, instead of sem 1,2

**Comment by AhmedThahir** [comment]
Alright then. Since you are fine with this, I'm closing this issue.
